version: '3.5'

services:
  app:
    build: .
    container_name: cars-management-api
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=3000
    dns:
      - 8.8.8.8
